//
//  APIService.swift
//  EUCities
//
//  Created by Aleksander Popek on 10/11/2020.
//

import Foundation

enum APIService: APIServiceProtocol {
    case getCities
    
    case getDetails
    
    case getMoreInfo
    
    case getImage(
        key:String
    )
    
    /// API baseURL.
    var baseURL: String {
        switch self {
        case .getCities,
             .getDetails,
             .getMoreInfo:
            return Config.APIBaseUrl
        case .getImage:
            return Config.ImagesBaseUrl
        }
    }
    
    /// The path that will be appended to API's base URL.
    var path: String {
        switch self {
        case .getCities:
            /// Path generated by mocky.io service that returns a custom built list of cities in JSON format
            /// Its possible to set a delay
            return "86c08063-6def-458d-b912-f7c6f020f80b"
        case .getDetails:
            /// Path generated by mocky.io service that returns details about some random city
            /// A delay was set to better simulate API response times
            return "4a6b40f1-e237-4df2-945f-d88f9e1d5bf1?mocky-delay=200ms"
        case .getMoreInfo:
            /// Path generated by mocky.io service that returns some random city description
            /// A delay was set to better simulate API response times
            return "16bca3dc-fe43-4603-abe7-0b3dc10444fa?mocky-delay=300ms"
        case .getImage(let key):
            /// Unsplash API path returning random photo
            return key
        }
    }
    
    /// The HTTP method.
    var method:String {
        return "GET"
    }
    
    /// The expected responseType.
    var responseType: ResponseType {
        switch self {
        case .getCities,
             .getDetails,
             .getMoreInfo:
            return .json
        case .getImage:
            return .image
        }
    }
}
